steps:
  - name: 'gradle:7.3.3-jdk8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="/builder/home/.gradle/wrapper/dists/gradle-7.3.3-bin/.../bin:$PATH"
        gradle clean build

        
#steps:
#- name: gradle:8-jdk8
#  entrypoint: gradle
#  args: ['test']
