steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean', 'build']
  env:
    - 'GRADLE_OPTS=-Dorg.gradle.daemon=false'
  dir: 'subdirectory'

#steps:
#- name: gradle:8-jdk8
#  entrypoint: gradle
#  args: ['test']
