---
# tasks file for project
- name: copy jar file
  ansible.builtin.copy:
    src: /var/lib/jenkins/workspace/demo/build/libs/demo.jar
    dest: /opt/demo.jar
- name: starting spring service
  shell: systemctl start spring.service
  
