on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
      - uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
